DELETE http://localhost:8080/events/4
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJhc3Vwcm90dGF5QGdtYWlsLmNvbSIsImV4cCI6MTczNTkxMDUxOCwidXNlcklkIjoyfQ.LL5Y67tMyOo6pAFlN_FkWLbldC0aI6vHzOWFHh0lGto
