POST http://localhost:8080/events/2/register
content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJhc3Vwcm90dGF5QGdtYWlsLmNvbSIsImV4cCI6MTczNTkwODcwMywidXNlcklkIjoyfQ.StwfKqfPzNCdhxCt9LuWgLPY4sWp6dLLP8Yi_rrEEdc
